### ISSUE TITLE
Unable to convert trained model to CoreML for iOS

### ISSUE THREAD

**Issue by yarodevuci** [koflerm/tensorflow-image-classifier#2]
I trained the model and cannot convert it using converters.
Getting this error: 
'No op found in the TF graph that produces the given output name(s)

Any suggestions ?

**Comment by rameeznkhan** [comment]
Try this command it will give you the output array 
`bazel run tensorflow/tools/graph_transforms:summarize_graph -- --in_graph=/tmp/model.pb
in_graph=/tmp/model.pb`
